# Generated by Django 4.2.4 on 2023-08-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uavs',
            fields=[
                ('UavID', models.AutoField(primary_key=True, serialize=False)),
                ('Brand', models.CharField(max_length=50)),
                ('Model', models.CharField(max_length=50)),
                ('Weight', models.IntegerField()),
                ('Image', models.CharField(max_length=50)),
                ('CategoryID', models.IntegerField()),
            ],
        ),
    ]
