# Generated by Django 3.2.19 on 2023-08-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UAVRental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=80, verbose_name='Brand')),
            ],
            options={
                'ordering': ['Brand'],
            },
        ),
        migrations.CreateModel(
            name='Uav',
            fields=[
                ('UavID', models.AutoField(primary_key=True, serialize=False)),
                ('Brand', models.CharField(max_length=50)),
                ('Model', models.CharField(max_length=50)),
                ('Weight', models.IntegerField()),
                ('Image', models.ImageField(default='', upload_to='images')),
                ('CategoryID', models.IntegerField()),
                ('genres', models.ManyToManyField(related_name='Uavs', to='UAVRental.Genre', verbose_name='Genres')),
            ],
            options={
                'ordering': ['Brand'],
            },
        ),
        migrations.DeleteModel(
            name='Uavs',
        ),
    ]
