# Generated by Django 3.2.19 on 2023-08-11 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UAVRental', '0002_auto_20230811_0714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uav',
            options={},
        ),
        migrations.RemoveField(
            model_name='uav',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
