# Generated by Django 3.2.19 on 2023-08-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UAVRental', '0003_auto_20230811_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uav',
            name='Image',
            field=models.CharField(max_length=50),
        ),
    ]
