# Generated by Django 3.2.19 on 2023-08-11 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UAVRental', '0004_alter_uav_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uav',
            new_name='Uavs',
        ),
    ]
