# Generated by Django 3.2.19 on 2023-08-12 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UAVRental', '0007_auto_20230812_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uav',
            fields=[
                ('UavID', models.AutoField(primary_key=True, serialize=False)),
                ('Weight', models.IntegerField()),
                ('Image', models.ImageField(default='', upload_to='images')),
                ('BrandID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UAVRental.brand')),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UAVRental.category')),
                ('ModelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UAVRental.model')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('RentalID', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerID', models.IntegerField()),
                ('BeginDate', models.DateTimeField(auto_now=True)),
                ('EndDate', models.DateTimeField(auto_now=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('UavID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UAVRental.uav')),
            ],
        ),
    ]
