# Generated by Django 3.2.19 on 2023-08-12 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UAVRental', '0008_rental_uav'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RentalID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UAVRental.rental')),
                ('UavID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UAVRental.uav')),
            ],
        ),
    ]
