# Generated by Django 3.2.19 on 2023-08-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UAVRental', '0009_rentalinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentalInfo',
        ),
    ]
