# Generated by Django 3.2.19 on 2023-08-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UAVRental', '0010_delete_rentalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='BeginDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='EndDate',
            field=models.DateTimeField(),
        ),
    ]
