# Generated by Django 3.2.19 on 2023-08-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UAVRental', '0012_uploadmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uav',
            name='ModelID',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
