# Generated by Django 3.2.19 on 2023-08-14 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UAVRental', '0014_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='UavID',
        ),
        migrations.DeleteModel(
            name='Uav',
        ),
    ]
