# Generated by Django 3.2.19 on 2023-08-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UAVRental', '0016_uav'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
